name: Pre-commit
on:
  pull_request:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Testing Complete
        uses: ./
        with:
          go-setup: true
          log-level: debug
          environment-file: ./.github/workflows/examples/complete/envFile.yaml
          template-path: ./.github/workflows/examples/complete/templates
          output-path: ./.github/workflows/examples/complete/outputs
      - name: View Report of Testing
        shell: bash
        run: |
          cat ./.github/workflows/examples/complete/outputs/*
      - name: Testing Summary
        uses: ./
        with:
          go-setup: true
          log-level: debug
          environments: |
            json_output="{\"files\": \"/gomodeler/files/file1.yaml /gomodeler/files/file2.json /gomodeler/files/file3.csv /gomodeler/files/file4.txt /gomodeler/files/file5.py\",\"files_path\": \"./templates/outputs\",\"working_dir\": \"/gomodeler\",\"items\": [\"item1\",\"item2\",\"item3\"],\"textIn\": {\"upperCase\": \"upper case testing\",\"lowerCase\": \"Upper Case Testing\",\"titleCase\": \"Title case testing\",\"capitalCase\": \"capital Case Testing\",\"pascalCase\": \"pascal case testing\",\"camelCase\": \"Camel case Testing\",\"snakeCaseLower\": \"Snake Case Lower Testing\",\"snakeCaseUpper\": \"Snake Case Upper Testing\",\"kebabCaseLower\": \"Kebab Case Lower Testing\",\"kebabCaseUpper\": \"Kebab Case Upper Testing\"}}"
          environment-file: ./.github/workflows/examples/summary/envFile.yaml
          template-path: ./.github/workflows/examples/summary/templates
          output-path: ./.github/workflows/examples/summary/outputs
          github-step-summary: true
