name: Pre-commit
on:
  pull_request:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Testing Complete
        uses: ./
        with:
          go-setup: true
          log-level: debug
          environment-file: ./.github/workflows/examples/complete/envFile.yaml
          template-path: ./.github/workflows/examples/complete/templates
          output-path: ./.github/workflows/examples/complete/outputs
      - name: View Report of Testing
        shell: bash
        run: |
          cat ./.github/workflows/examples/complete/outputs/*
      - name: Testing Summary
        uses: ./
        with:
          go-setup: true
          log-level: debug
          environments: |
            json_output="{\n    \"files\": \"/gomodeler/files/file1.yaml /gomodeler/files/file2.json /gomodeler/files/file3.csv /gomodeler/files/file4.txt /gomodeler/files/file5.py\",\n    \"files_path\": \"./templates/outputs\",\n    \"working_dir\": \"/gomodeler\",\n    \"items\": [\n        \"item1\",\n        \"item2\",\n        \"item3\"\n    ],\n    \"textIn\": {\n        \"upperCase\": \"upper case testing\",\n        \"lowerCase\": \"Upper Case Testing\",\n        \"titleCase\": \"Title case testing\",\n        \"capitalCase\": \"capital Case Testing\",\n        \"pascalCase\": \"pascal case testing\",\n        \"camelCase\": \"Camel case Testing\",\n        \"snakeCaseLower\": \"Snake Case Lower Testing\",\n        \"snakeCaseUpper\": \"Snake Case Upper Testing\",\n        \"kebabCaseLower\": \"Kebab Case Lower Testing\",\n        \"kebabCaseUpper\": \"Kebab Case Upper Testing\"\n    }\n}"
          environment-file: ./.github/workflows/examples/summary/envFile.yaml
          template-path: ./.github/workflows/examples/summary/templates
          output-path: ./.github/workflows/examples/summary/outputs
          github-step-summary: true
